### ISSUE TITLE
Is it multi-threaded?

### ISSUE THREAD

**Issue by Wandalen** [drifting-in-space/limelight#4]
Hi! Thanks for Open Source.
Is that thing multi-threaded? If not why it uses yew?

**Comment by paulgb** [comment]
Hi Wandalen, no, it’s not multi-threaded. The core limelight crate does not
use Yew; the limelight-yew crate just makes it a bit easier to add
limelight to an app that uses Yew.

— Paul

**Comment by Wandalen** [comment]
Is multi-threading planned? Thanks.

**Comment by paulgb** [comment]
I don’t intend on supporting multi-threading directly, but depending on
what you want to do it may already be possible. If you just want to run
outside the browser’s UI thread, you could run limelight in a WebWorker and
pass it an OffscreenCanvas from the UI thread. Browser support for that is
pretty spotty, though:
https://caniuse.com/offscreencanvas

If you tell me a bit more about your use case, I may be able to point you
in the right direction.

**Comment by Wandalen** [comment]
Aha. Thanks for the answer.
